# Generated by Django 4.2.7 on 2023-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Health and Beauty', 'Health and Beauty'), ('Office', 'Office'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Tools', 'Tools'), ('Toys and Games', 'Toys and Games'), ('Miscellaneous', 'Miscellaneous')], max_length=20, null=True),
        ),
    ]
