# Generated by Django 4.2.7 on 2023-12-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Message'},
        ),
    ]
